version: '3'

services:
  web:
    build:
      context: ./web
    volumes:
      - ./sample:/httpd/htdocs/arf/passwdweb
    ports:
      - "0.0.0.0:8080:80"
    container_name: web
    privileged: true
    tty:  true